### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by shayanz23** [ZombieStriker/PluginConstructorAPI#7]
```
Found a new version of PluginConstructorAPI: v1.1.53 downloading now!!
[08:39:57 INFO]: Done (8.278s)! For help, type "help"
[08:39:57 INFO]: Timings Reset
[08:39:58 WARN]: java.io.FileNotFoundException: https://github.com/ZombieStriker/PluginConstructorAPI/releases/download/v1.1.53/PluginConstructorAPI.jar
[08:39:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[08:39:58 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[08:39:58 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[08:39:58 WARN]:        at java.base/java.net.URL.openStream(Unknown Source)
[08:39:58 WARN]:        at PluginConstructorAPI.jar//me.zombie_striker.pluginconstructor.GithubUpdater$1.run(GithubUpdater.java:56)
[08:39:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[08:39:58 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:39:58 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:39:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:39:58 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:39:58 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

This is happening when I start my papermc minecraft server for the first time. It tries to download the jar from 
https://github.com/ZombieStriker/PluginConstructorAPI/releases/download/v1.1.53/PluginConstructorAPI.jar
but there's nothing there.

**Comment by shayanz23** [comment]
I think this would work:
https://github.com/ZombieStriker/PluginConstructorAPI/releases/download/v1.1.53/PluginConstructorAPI-1.1.53.jar

**Comment by jsinc-sebastian** [comment]
> I think this would work: https://github.com/ZombieStriker/PluginConstructorAPI/releases/download/v1.1.53/PluginConstructorAPI-1.1.53.jar

So I'm just extracting the JAR to ZIP and modify the contents?
